name: pwd
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: List Files
        run: |
          pwd
          ls
